### ISSUE TITLE
Task 3.3: Edge prevented the speedtest from running

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#100]
It blocked flash initially. Eventually, it recovered and ran, but not until it popped up a nastygram:
![image](https://user-images.githubusercontent.com/4753203/32857766-9c75ffd6-ca0e-11e7-9158-588338804e47.png)

**Comment by Anghus** [comment]
I'm not sure what to do about this one. Maybe we can put an alert in there about this behavior? Saving this one for Doug to look at. Nonetheless, it's not a big priority.

**Comment by DouglasSteen** [comment]
Updated the task to use native "Speed test" in Bing search results (which works great in Edge). See following text:

"(1) Select Knowledge, and review the note. (2) In Microsoft Edge, in Search, type speed test. (3) In Bing results, under Speed test, select Start. (4) Complete the test, and note the performance. (5) Close Microsoft Edge."
