### ISSUE TITLE
Task 4.1: Alert incorrectly claims you can paste from the local device

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#102]
I have not been able to paste from notepad on the local device to a VM in LODS, at least in Chrome and Firefox (I do not have access to Edge at present). If this works on Edge, please invalidate.

**Comment by Anghus** [comment]
In some browsers, you have to use the toolbar to paste text from the clipboard in to the VMs: Commands (lightning bolt), Paste, Paste Clipboard Text. We should document this in the next go around. Saving for the next release.

**Comment by DouglasSteen** [comment]
Task 4.1 is talking about copying the Azure Pass codes and Valorum credentials to Notepad on the local device (not the other way). I have confirmed this works in Microsoft Edge. Also, the participant has already learned how to copy text from the local device into the VM earlier in the lab (under Exercise 1).
