### ISSUE TITLE
Task 7.1: Subscription did not appear

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#112]
The first time I did this, no subscription showed up. I closed Edge and reopened it, navigated back to the portal, and the subscription appeared. Not sure if this is a timing thing, or a refresh thing. Screenshot below:
![image](https://user-images.githubusercontent.com/4753203/32859826-4127524a-ca15-11e7-8127-421face59704.png)

**Comment by Anghus** [comment]
Added an Alert about this.
