### ISSUE TITLE
Step 10.4: Completion message indicates the lab is not over

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#116]
This is the exercise completion message, but this is the last exercise of the lab:
In this exercise, you learned how to configure an Intune subscription. Later in the lab, you'll configure Azure AD to enroll devices in Intune automatically when the user joins a device to Azure AD. This integration between Azure AD and Intune allows you to better manage Windows devices the moment they join Azure AD.

**Comment by Anghus** [comment]
Fixed. Looks like a copy/paste error from our Windows Store for Business lab.
