### ISSUE TITLE
Need to disable Automatic Updates

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#118]
On DC at least.

**Comment by chris-howie** [comment]
Why is this assigned to me? I do not manage the VMs...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Anghus** [comment]
Yup. Assign to Doug.

________________________________

**Comment by Anghus** [comment]
Doug disabled Windows Update for all of the VMs today. Closing.
