### ISSUE TITLE
Task 2.2 and 4.1: The alert seems to have more text than the box allows

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#121]
And doesn't present scroll bars:
![image](https://user-images.githubusercontent.com/4753203/32862281-3f2a0a2a-ca1d-11e7-9621-bc3faec6e171.png)

FYI - I am testing on Chrome this afternoon, as I don't have Edge available, so there is the possibility this is a browser-specific issue. 

Finally, based on what I can read of it, it seems like this text possibly should be a knowledge box anyhow.

**Comment by Anghus** [comment]
I get a scrollbar. It's very thin, though. I moved this to a Knowledge box instead of an Alert. Did the same for both tasks.
