### ISSUE TITLE
Task 2.5: Sub-task 10 has a redundant select

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#125]
It states:
(8) Select the Members tab, and then select Add. (9) In Enter the object names to select, type adfssvc, and then select OK. (10) Select the Members tab, and then select Add.

However, you are already on the Members tab in step 10.

**Comment by Anghus** [comment]
Fixed. Changed to "(8) Select the Members tab, and then select Add. (9) In Enter the object names to select, type adfssvc, and then select OK. (10) On the Members tab, and then select Add. (11) In Enter the object names to select, type Lori, and then select OK."
