### ISSUE TITLE
Task 2.7: Text doesn't line up with options

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#128]
In sub-task 6, the option requested is not an available option. The closest is Windows 8 / Windows Server 2012. 

Text:
(6) From the Certification Recipient list, select Windows Server 2012 R2. 

Image:
![image](https://user-images.githubusercontent.com/4753203/32863215-5a4be5fa-ca20-11e7-9cfc-4b6491bad7cb.png)

Also, the label is Certificate Recipient, not Certification Recipient.

**Comment by Anghus** [comment]
Fixed. Change to "(6) From the Certificate Recipient list, select Windows 8.1 / Windows Server 2012 R2"
