### ISSUE TITLE
Task 2.11: Multiple icons show

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#129]
The text states:
(1) Select Start, and then type DNS. (2) Select DNS to open the DNS management console. 

However, more than one thing named DNS shows, and the top one on the list is the actual DNS server executable:
![image](https://user-images.githubusercontent.com/4753203/32863457-2a8755a6-ca21-11e7-8edc-1a0f5dc809d3.png)

**Comment by Anghus** [comment]
Fixed. Changed to "(2) Select DNS (Desktop app) to open the DNS management console."
