### ISSUE TITLE
Task 1.2: There is no CM console on the taskbar

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#14]

**Comment by Anghus** [comment]
Verified that it's still not on the task bar. Need @DouglasSteen to look at this.

**Comment by DouglasSteen** [comment]
Will update this when all lab testing is complete and I will do one final spin up of all the VMs and make any updates that are needed (including this one).

**Comment by DouglasSteen** [comment]
Per Jerry, no other updates are needed. I added the Configuration Manager console to the taskbar for the CORP\Mark sign in. I verified that the Configuration Manager console launches successfully. Updated all the domain-joined virtual machines to make certain that machine passwords stay in sync. This one is closed and ready to ship virtual machines.
