### ISSUE TITLE
Stylistic difference in directions?

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#145]
Not sure if this is something we want to bug, but the directions on several tasks throughout the lab are a bit different than what I have normally seen. As an example, Task 2.7 states:
(2) On the Scope tab, under Security Filtering, remove Authenticated Users. You can ignore and close any warnings about removing Authenticated Users.

It seems like the normal style is something like this:
(2) On the Scope tab, under Security Filtering, select Authenticated Users, then select Remove. Select OK to dismiss the warning dialog.

**Comment by Anghus** [comment]
Because this is a repurpose lab, the instructions do read a little different.
