### ISSUE TITLE
Task 3.3: Missing spaces and impropper bolding (looks like the LODS import/export bug)

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#146]
(1)Review the Knowledgebox. (2)At the PowerShell prompt, type MSInfo32 to view System Information. (3) Scroll down to the bottom of the System Summary details pane, and view Device Guard Security Services Configuredand Device Guard Security Services Running.(4)Close System Information.

**Comment by Anghus** [comment]
Fixed. What a mess.
