### ISSUE TITLE
Multiple Tasks: Directs to right-click on an object without expanding first

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#153]
Task 6.3, 7.4, 7.6

At this point, all folders are collapsed.

**Comment by Anghus** [comment]
Since I don't think this is going to prevent someone from sailing through the task, I'm going to defer this until the next release.

**Comment by DouglasSteen** [comment]
Updated the task to first navigate to the folder in question and then right-click the folder. See the following update to the task:

"(1) In the console tree, go to Certificates – (Local Computer)\Personal\Certificates . (2) In the console tree, right-click the Certificates – (Local Computer)\Personal\Certificates folder, point to All Tasks, and then click Request New Certificate. (3) Click Next, and then click Next again. (4) Select the Kerberos Authentication certificate template, and then click Enroll. (5) Click Finish."
