### ISSUE TITLE
Task 6.4: Directs to export wrong cert

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#154]
Task states: 
(1) Right-click the Kerberos Authentication certificate issued to DC.corp.contoso.com (the second certificate), point to All Tasks, and then click Export. 

However, in my lab, this was the third cert, not the second. 

![image](https://user-images.githubusercontent.com/4753203/32900026-190e7fe8-cab2-11e7-9246-6f5b3b43de6b.png)

**Comment by Anghus** [comment]
Fixed by changing to "(1) Right-click the Kerberos Authentication certificate issued to DC.corp.contoso.com (check the Certificate Template column), point to All Tasks, and then click Export."
