### ISSUE TITLE
Odd character in lab intro

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#174]
Explain how Windows Defender EG and ATP can mitigate security threats that antimalware applications, including Windows Defender, **donâ€™t** ordinarily detect.

**Comment by Anghus** [comment]
Closing this one as the lab will remain in development until the bits are available in the images.

**Comment by Anghus** [comment]
Went back and had another look. This is a problem with the lab profile. I went ahead and fixed it.
