### ISSUE TITLE
Task 1.1: Missing steps to log into system

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#175]
This task begins assuming you are already logged in. Also unsure which system to log into. I tried all three systems, but the steps mentioned do not work on any of them when logging in with the first account in the logon list. 

![image](https://user-images.githubusercontent.com/4753203/32921837-d61d38f8-caf4-11e7-8a90-87b83ed2b00f.png)

**Comment by Anghus** [comment]
Closing this one as the lab will remain in development until the bits are available in the images.
