### ISSUE TITLE
Task 3.2: Edge fails to open file on first try

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#183]
This is the second time I've seen this in two separate labs. I am beginning to suspect it has something to do with the initial setup junk Edge tries to do. Regardless, it's not a good look to say "Edge may decide to die in a fire; if so, please close it and try again." It does tend to work, however, if you just close it and try again. 

![image](https://user-images.githubusercontent.com/4753203/32924043-684367a6-cb00-11e7-9a58-c5cf3fa5b246.png)

**Comment by networkingguru** [comment]
Just confirmed this is not due to the Edge first run behavior by opening it once before trying to open the xml. This seems to be a legitimate issue in Edge where for some inexplicable reason, it will not open an xml file until after it has failed to do so once.

**Comment by Anghus** [comment]
We need Doug to look at this. Since it doesn't prevent a successful completion of the lab, I'm only marking it as a medium priority. However, if there is a simple fix, we should do it.

**Comment by Anghus** [comment]
Removing this bug from this lab, making it a general bug.

**Comment by DouglasSteen** [comment]
Unable to resolve this issue as we sign in as new users on a device. This seems to be something in the user profile that will be present when a new user signs in.

As a work around, always use Internet Explorer to open XML files. It consistently works first time :)

I updated the lab in question (HOL-SC1-3A) to open XML files with Internet Explorer.
