### ISSUE TITLE
Task 3.3: Bolding errors throughout the knowledge box

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#186]
Every ** is a bolding error, as that's how markup specifies bold. This is probably due to missing spaces (LODS bug, of course). Example:
**Hash.**This level specifies individual hash values for each discovered binary. Although this level is specific, it requires additional administrative overhead to maintain the current product versions’ hash values. Each time a binary is updated, the hash value changes, therefore requiring a policy update.
**FileName.**This level specifies individual binary file names

**Comment by Anghus** [comment]
Fixed.
