### ISSUE TITLE
Task 10.7: Step missing

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#202]
The task states:
(2) In the GPMC, in the console tree, go to Group Policy Management\Forest: corp.contoso.com\Group Policy Objects. (3)  In the details pane, on the Scope tab, under Security Filtering, click Authenticated Users, and then click Remove. 

However, you need to expand the Group Policy Objects and select the correct GPO to perform step 3.

**Comment by Anghus** [comment]
I fixed by adding "EnableDeviceGuard – Example CCI Policy" to the path.
