### ISSUE TITLE
Task 12.4: Workstation password corrupt after revert

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#208]
After the revert, GPupdate would not work, though network connectivity was fine:
![image](https://user-images.githubusercontent.com/4753203/32926844-0c154918-cb0f-11e7-8396-5bf7f00dfac2.png)

In checking the event logs, I found an access denied, which reminded me of broken workstation trust relationship issues you sometimes get with cloning:
![image](https://user-images.githubusercontent.com/4753203/32926863-2f2b1860-cb0f-11e7-90d0-f35672e5c09e.png)

I removed the workstation from the domain and tried to rejoin it, but it would not join. The system is claiming a name resolution issue (DC not found), but the DC is available (I can ping it by name) and the srv is resolvable from the client:
![image](https://user-images.githubusercontent.com/4753203/32927162-ba73d906-cb10-11e7-9bbb-cf42bb210e34.png)

![image](https://user-images.githubusercontent.com/4753203/32927179-c7fad7c8-cb10-11e7-834f-87ced4f0899b.png)

The only real error I get in the event log is a licensing error. 
![image](https://user-images.githubusercontent.com/4753203/32927218-f854ab4c-cb10-11e7-8919-dcf72b46b782.png)

Can lack of licensing cause a domain join failure? Regardless, this is a blocker.

**Comment by Anghus** [comment]
Doug has created new differencing disks after resetting the machine passwords for all of the VMs.
