### ISSUE TITLE
Task 2.2: Should we be using Edge instead of IE?

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#219]
Lab repeatedly directs to use IE, so if we want to change it to Edge, we should change all occurrences.

**Comment by Anghus** [comment]
I'm not sure why we're using IE and not Edge, but I don't want to change it now. We've tested using IE. I'd like to switch this over in the next release, though.

**Comment by chris-howie** [comment]
Honestly, I haven't personally gone back to using Edge since the early compatibility issues. We would need to test the lab using Edge before making the switch for sure but I'm definitely open to it.
