### ISSUE TITLE
Task 2.3: When doing the labs back to back, this task is superfluous

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#221]
I'm not sure what the expected scenario is for these labs, but if attendees will be doing them like I am, this step is a bit confusing. The alert tells you that you won't be prompted to select the MDM authority twice, but it takes a second before you realize that is why nothing on the page lines up with the directions and you basically need to skip this step.

**Comment by Anghus** [comment]
Looks like Chris added an Alert for this already. I'm happy with this solution.
