### ISSUE TITLE
Task 4.8: Settings do not match text

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#222]
Can't figure out where to go to set the setting requested. The text states:
(1) In Device **Complance**, select Compliance policy settings. (2) Beside Treat "No Policy Assigned" devices as, **seelct** Non compliant, and then select Save.

However, this is what I see:
![image](https://user-images.githubusercontent.com/4753203/32966253-d3590142-cb9e-11e7-82aa-d73a9b27d5e5.png)

Also, two words are misspelled (bolded in the text above)

**Comment by Anghus** [comment]
@networkingguru can you confirm that skipping this step did not hurt the lab's outcome? If so, @chris-howie needs to remove this step.

**Comment by chris-howie** [comment]
I'll pull this task right now. One of those random UI differences. :/
