### ISSUE TITLE
Task 5.4: Additional security prompt appears

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#223]
The text states the following:
(1) In Settings, select lori@domain.onmicrosoft.com, and then select Info. (2) Select Sync, and then wait for the sync to finish.

However, this is what appears immediately following task 5.3:
![image](https://user-images.githubusercontent.com/4753203/32970923-9aaab9a0-cbb0-11e7-89fa-994b31838a06.png)

**Comment by networkingguru** [comment]
![image](https://user-images.githubusercontent.com/4753203/32971935-4e3ad4ba-cbb5-11e7-83cc-78ba72431c55.png)

![image](https://user-images.githubusercontent.com/4753203/32971941-551e124c-cbb5-11e7-9a61-7c0c95756691.png)

**Comment by networkingguru** [comment]
Had to set a password, but missed that screenshot :( I picked the existing one (Passw0rd)

Then I got this:
![image](https://user-images.githubusercontent.com/4753203/32972066-ee0f6ece-cbb5-11e7-8852-81c487aa4b25.png)

I skipped the PIN by canceling it, and got this:
![image](https://user-images.githubusercontent.com/4753203/32972094-115d8b9a-cbb6-11e7-8e4f-2a6d075b624d.png)

**Comment by networkingguru** [comment]
Looks like I'm back on track after this.

**Comment by Anghus** [comment]
Is all this happening when you first sign on to the VM?

**Comment by networkingguru** [comment]
No. It happens directly after step 5.3, which is:
(1) Select Connect. (2) In Set up a work or school account, type lori@domain.onmicrosoft.com, where domain is the tenant you were assigned in HOL-SC1-1A, with a password of Passw0rd, and then select Next. (3) In Password, type Passw0rd, and then select Sign in.

**Comment by Anghus** [comment]
Okay. We’ll have to figure out why this extra stuff is coming up on our pooled tenants.

**Comment by Anghus** [comment]
I need @chris-howie to look at this bug. However, he can't do that until we get some new tenants from Matt. I'll send a reminder to Matt tonight.

**Comment by chris-howie** [comment]
Fixed
