### ISSUE TITLE
Swap exercises 5 and 6?

### ISSUE THREAD

**Issue by michelle-anderson** [HoneycuttInc/Thorncastle#231]
Exercise 5 mentions a malware attack that hasn't happened, yet. Should we move exercise 6 earlier in the lab?

**Comment by DouglasSteen** [comment]
Updated Exercise 5 introduction and conclusion to include this sentence "The security attack was performed by the  detection test script that you ran earlier in this lab."   This helps clarify why the simulated attack occurs before Exercise 5. Exercise 6 is referencing a different simulated attack.
