### ISSUE TITLE
Task 1.1: Cannot login as Lori@domain.onmicrosoft.com

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#232]
The lab assumes that this system is connected to Azure (perhaps maintaining the state from the last lab?), but it is not:
![image](https://user-images.githubusercontent.com/4753203/32976514-1265fcf8-cbdd-11e7-8ec0-5d0d4983b5e4.png)

**Comment by Anghus** [comment]
I'd prefer that @chris-howie look at this bug when I'm done with the others.

**Comment by chris-howie** [comment]
This should just say "lori", not "Lori@domain.onmicrosoft.com". Not sure when that got added.

**Comment by chris-howie** [comment]
Changed
