### ISSUE TITLE
Task 2.5: Group is labeled the Protection group

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#238]
Step states:
(3) On the Ribbon, in the Sensitivity group, select Protection, and then select Confidential > All Contoso Employees.

However, this is what I see:
![image](https://user-images.githubusercontent.com/4753203/32982673-cb2bd814-cc4d-11e7-99c2-5ad4a7b2ef3e.png)

**Comment by Anghus** [comment]
Fixed.
