### ISSUE TITLE
General: CM is a bit slow

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#257]
Lags a bit, to the point that occasionally you are not sure if it took your change. Not sure if more resources to the VM would help or not.

**Comment by Anghus** [comment]
@DouglasSteen, can you take a look?

**Comment by Anghus** [comment]
Doug, if there is nothing we can do, mark this as Out of Scope and Release Notes.

**Comment by DouglasSteen** [comment]
CM already has 8GB of memory assigned to the VM. I think this is an issue of disk activity or just performance of the Hyper-V hosts we are running these labs on. The processor and memory resources are well within "normal" performance values. My hunch is that we are suffering from poor disk performance.

See screenshot attached:

<img width="960" alt="thorncastle-issue-257-cm-systemresources" src="https://user-images.githubusercontent.com/31675871/33109643-aaebcad0-cef7-11e7-85ce-8e9ceadcc2b5.png">
