### ISSUE TITLE
Task 3.1: Split commands in to separate tasks

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#27]
There are three different commands in this task. If we split this out in to separate tasks, each task can have its own Type Text button to help eliminate user error.

**Comment by chris-howie** [comment]
We have an alert in there to discuss the multiple command prompts (so that the DLL can be loaded). I'm afraid breaking this task up may be more confusing.

**Comment by Anghus** [comment]
Closing this based on Chris's feedback.
