### ISSUE TITLE
Task 2.1: Steps are not consistent with current state

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#276]
Steps direct to:
(1) Select Switch to Machine. (2) Sign in to WIN10-01 as CORP\Mark with the password Passw0rd. (3) In Microsoft Edge, open https://portal.azure.com. (4) Sign in to the Azure portal as mark@domain.onmicrosoft.com, where domain is the tenant you were assigned in HOL-SC1-1A, **wiith** the password Passw0rd.

However, we are already on Win10-01 and logged in as Mark, so all we really need to do is steps 3 and 4. Also, With is misspelled (bolded above)

**Comment by pr-honey** [comment]
Fixed.
