### ISSUE TITLE
Task 3.4: Directives do not match screen

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#284]
The text states:
(1) In the settings app, select Mark@domain.onmicrosoft.com, then select Info. (2) Select Sync and wait for the sync to complete.

However, this is what I see:
![image](https://user-images.githubusercontent.com/4753203/32985474-98bfe396-cc81-11e7-94d5-ffb64abffc5b.png)

**Comment by pr-honey** [comment]
I modified this task-- if the lab tenant is set up with AAD Premium the device should auto-enroll. You can verify that it's enrolled with the steps in the section "To verify the installation of the client software from the Microsoft Intune administrator console" at https://docs.microsoft.com/en-us/intune-classic/deploy-use/install-the-windows-pc-client-with-microsoft-intune

I found one reference that said the Info button won't appear for at least 30 minutes. I don't know if that's true or not. I still haven't seen it.

**Comment by pr-honey** [comment]
This is happening because the machine isn't actually being managed by Intune. Not sure why yet.

**Comment by pr-honey** [comment]
Fixed.
