### ISSUE TITLE
General: Performance is bad

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#288]
VM is very sluggish. Maximizing IE looked like stop-motion animation.

**Comment by Anghus** [comment]
Moving this bug over to Doug's list. @DouglasSteen, the VM in question is BYOD.

**Comment by DouglasSteen** [comment]
Increased memory to 4GB for this virtual machine. See the attached screenshot for available system resources with only 3GB. The 

<img width="960" alt="thorncastle-issue-319-taskmanager-resources" src="https://user-images.githubusercontent.com/31675871/33109712-0eaeea02-cef8-11e7-8d01-a2cb2f8045c4.png">
