### ISSUE TITLE
Task 3.3: Restarting the AD FS service

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#29]
We just restarted the service in the previous step, and now we're asking to restart it again. Are both restarts necessary? Additionally, the current step says, "Restart the AD FS server for the registration and group memberships to take effect." We need to provide actual step-by-step instructions.

**Comment by Anghus** [comment]
The very next step has instructions for restarting the service. I removed the text from the previous step. Still need to verify whether both restarts are actually necessary. Lower priority now.

**Comment by chris-howie** [comment]
Haha, yes this is actually necessary. The first restart is required to be able to use that provider in the next task, then the second restart is needed to actually use the adapter. Technically the second restart is only necessary if we were actually going to use it but I think it should stay just in case if we add that part. :)
