### ISSUE TITLE
Task 2.3: Another odd splash screen

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#292]
Immediately after step 1, I got this:
![image](https://user-images.githubusercontent.com/4753203/32987762-d8363e52-ccb9-11e7-9613-ad7f6d3658cb.png)

**Comment by Anghus** [comment]
Same. Odd pop ups that students will know to dismiss can be treated as assumed knowledge. We don't document odd pop ups like these because they change almost daily.
