### ISSUE TITLE
Task 3.1: Instructions are a bit nebulous

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#298]
Task states:
(2) In the Windows PowerShell window,, type ping followed by the domain name of your SharePoint site from the URL you noted in the previous exercise—for example, ping contoso.sharepoint.com. 

I assume the "URL you noted" means the URL we pasted into notepad, but I think this would be more direct if we just said that.

**Comment by Anghus** [comment]
Updated language as you described.
