### ISSUE TITLE
Task 4.1: RSAT update already installed on VM

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#30]
The instructions tell the student to download and install RSAT. However, when I run the RSAT update, it tells me that the update is already installed on the computer. Please verify. For tomorrow's event, it's not blocking anybody from using the lab.

**Comment by chris-howie** [comment]
HAHA, I think I asked Doug to install RSAT on that VM... When I first wrote it, it was not there of course.

**Comment by chris-howie** [comment]
I will check this to verify.

**Comment by chris-howie** [comment]
Fixed.
