### ISSUE TITLE
Task 3.5: Directives don't match menu

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#301]
Directions state:
(1) Select Allowed apps, and then select Add apps. (2) In the list, select Microsoft Edge, and then select OK. (3) Select OK to return to the policy configuration.

This is what I see:
![image](https://user-images.githubusercontent.com/4753203/32987888-04813eaa-ccbd-11e7-925d-eb7e572e2f63.png)

**Comment by Anghus** [comment]
Need @chris-howie to look at this one.

**Comment by chris-howie** [comment]
This was an O365 change. Fixed.
