### ISSUE TITLE
Task 5.5: "Windows Defender Advanced Threat Protection" not available

### ISSUE THREAD

**Issue by pr-honey** [HoneycuttInc/Thorncastle#302]
Running through SC1-1A to test my own lab, I found that I didn't see the Defender ATP option called for in 5.5. Also, in the text for step 2 there's a typo ("**Advaned**" instead of "advanced").

**Comment by Anghus** [comment]
@pr-honey, where did you get the tenant that you were testing? Did you use one of the tenants that I posted to the General channel or the tenant you were assigned in the first lab?

**Comment by Anghus** [comment]
Fixed the typo and waiting on Paul's answer before closing this bug.
