### ISSUE TITLE
Task 6.1: screen doesn't match instructions

### ISSUE THREAD

**Issue by pr-honey** [HoneycuttInc/Thorncastle#303]
Even in private mode, navigating to portal.azure.com takes me immediately to the MS account login page, with no "ready to get started" links in either the old or new sign-in experiences. I had to log in with the admin@lodseXXXX account before I got the "Confirm Microsoft Account" link mentioned in step 3 of this task.

**Comment by Anghus** [comment]
@DouglasSteen, can you take a look?

**Comment by DouglasSteen** [comment]
The "Type Text" control was correctly using https://www.microsoftazurepass.com. However, the task was saying to use http://portal.azure.com. 

Changed the text for the step as follows:

(1) In Internet Explorer, in the address bar, type https://www.microsoftazurepass.com (or select Type Text), and then select Enter. (2) On Ready to get started, select Start. (3) On The following Microsoft Account will be used for Azure Pass, select Confirm Microsoft Account.
