### ISSUE TITLE
Task 3.6: Directives do not match menu

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#305]
Text:
(1) Under Required settings, select Configure required settings. (2) In Required settings, under Windows Information Protection mode, select Hide Overrides. 

UI:
![image](https://user-images.githubusercontent.com/4753203/32991915-3470d038-cd0a-11e7-9dc1-4c8acda8808c.png)

**Comment by Anghus** [comment]
Need @chris-howie to look at this one.

**Comment by chris-howie** [comment]
Also a UI change. Fixed.
