### ISSUE TITLE
Task 3.14: Had to search for group

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#308]
The text states:
(1) In the list of policies, select MAM-WE SharePoint Online Block Policy. (2) Select Assignments, and then select Select groups. (3) In the list of groups, select MAM Users Group, and then select Select. 

However, the MAM users group did not show for me until I entered 'MAM' in the search box:
![image](https://user-images.githubusercontent.com/4753203/32992097-1d67b7a6-cd0c-11e7-8981-77eae33528a5.png)

**Comment by Anghus** [comment]
@chris-howie needs to look at this one.

**Comment by chris-howie** [comment]
Dammit, I swear they keep changing the functionality of the search box! I'll add this right now.
