### ISSUE TITLE
Task 5.2: Selecting "Restore Default..." doesn't seem to do anything

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#309]
Not sure if this is expected or not, but the URLS are already at the defaults. I had to make a change and then click the restore link to convince myself it was working.

**Comment by Anghus** [comment]
I ran in to this before. @chris-howie? It's a little confusing.

**Comment by chris-howie** [comment]
When I wrote this lab, I wasn't sure if those would be changed for any reason. Having them set to default is critical for the lab functioning correctly. If the values not changing is confusing, I can either add an additional note about the reasoning for the step or remove it. @Anghus - what would you prefer?

**Comment by chris-howie** [comment]
Removed subtask.
