### ISSUE TITLE
Task 8.3: Got Outlook initial setup screen

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#318]
![image](https://user-images.githubusercontent.com/4753203/32993698-7d2a9f72-cd21-11e7-957c-cb00513b9863.png)

**Comment by Anghus** [comment]
We should probably walk them through this. @chris-howie We can't dismiss this one as assumed knowledge, unfortunately.

**Comment by chris-howie** [comment]
I originally wasn't sure if this would be happening in my lab or not (it only happens the first time you access the mailbox). I'll add this now, since my lab is the first time the participant logs in as Lori.
