### ISSUE TITLE
Task 1.3: Edge has hung on Cornell page multiple times

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#319]
I've run through this four times now, and it's hung twice. I think the VM may need more RAM (looks like it has 3GB currently).

**Comment by pr-honey** [comment]
@DouglasSteen, is there anything you can do for us here?

**Comment by Anghus** [comment]
Another one for BYOD, @DouglasSteen.

**Comment by DouglasSteen** [comment]
Unable to reproduce the issue. Spin up the lab and then open the Cornell page without any problems. Did so six (6) consecutive times. Memory does not seem to be an issue (however disk utilization is high), see the attached screenshot. 

I upgraded the memory to 4,096.... But, it is more likely that we are having performance/resource issues with the platform (Hyper-V hosts), not the individual VMs.

<img width="960" alt="thorncastle-issue-319-taskmanager-resources" src="https://user-images.githubusercontent.com/31675871/33087161-a328d0ee-ce9e-11e7-99e8-402dc29d0cfd.png">
