### ISSUE TITLE
Task 4.1: Steps missing?

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#322]
The task states:
(1) In Intune, select Device configuration. (2) In Device configuration, select Profiles. (3) From the top menu, select Create profile.

However, this is directly following rebooting Win10-02. Should we be on Win10-01?

**Comment by networkingguru** [comment]
In conversation with Paul, there should be a switch to machine button and a directive to switch back to Win10-01 for this step.

**Comment by pr-honey** [comment]
Fixed
