### ISSUE TITLE
Task 4.5: Steps missing

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#323]
The end of task 4.4 leaves me here:
![image](https://user-images.githubusercontent.com/4753203/32994313-f1e397e8-cd2a-11e7-9128-e98497b2c3ba.png)

To get to where the directions want me to go, I need to: 1) Close Screen Lock 2) Close Device Configuration

**Comment by pr-honey** [comment]
Fixed-- added steps to end of 4.4
