### ISSUE TITLE
Task 5.1: UI does not match steps

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#327]
The steps listed are:
(1) Select Switch to Machine. (2) Sign in to WIN10-01 as CORP\Mark with the password Passw0rd.  (3) Select Start > Settings. (4) Select Accounts, and then select Access work or school. (5) In Access work or school, select Connected to contoso…. (6) Select Info. (7) Select Sync.

However, it doesn't appear that the machine is enrolled:
![image](https://user-images.githubusercontent.com/4753203/32994411-af86d3ea-cd2c-11e7-9286-64567582bf7e.png)

**Comment by pr-honey** [comment]
Yep. This is the issue I'm hoping @chris-howie  can shed some light on.

**Comment by pr-honey** [comment]
Fixed!
