### ISSUE TITLE
Task 1.7: Got prompted to open or save

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#329]
![image](https://user-images.githubusercontent.com/4753203/32996974-84406cbe-cd4f-11e7-8df9-39f0e485deeb.png)

**Comment by Anghus** [comment]
Need to update the instructions, @pr-honey.

**Comment by pr-honey** [comment]
Holding on this until we decide what to do with #330

**Comment by Anghus** [comment]
Replied to the other bug.

________________________________

**Comment by pr-honey** [comment]
Fixed by switching this task to BYOD.
