### ISSUE TITLE
Task 1.7: Server can't open PDF

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#330]
![image](https://user-images.githubusercontent.com/4753203/32996982-aa37a360-cd4f-11e7-9461-4e97377f357a.png)

**Comment by Anghus** [comment]
Oh, snap. Adding @DouglasSteen to this bug. Doug, we had to move this lab over to DC because we require Silverlight. What do you recommend for opening PDF files?

**Comment by pr-honey** [comment]
We could probably have the student open the PDF on BYOD; it's got Edge. It would mean a few more switches as the student goes between the PDF and various consoles.

**Comment by Anghus** [comment]
Let's do that. It's the least invasive solution.

________________________________

**Comment by pr-honey** [comment]
Fixed now.
