### ISSUE TITLE
Task 3.2: Got prompted to set a PIN

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#333]
I just canceled by clicking the X:
![image](https://user-images.githubusercontent.com/4753203/32997106-15d8fd34-cd51-11e7-912b-e619f8aec2e2.png)

**Comment by Anghus** [comment]
is this part of the verification after enrolling in management? If so, it should be covered in the generic step. Otherwise, we need to add a step for them to close the window.

**Comment by pr-honey** [comment]
I added a step to set the PIN.
