### ISSUE TITLE
Task 5.1: Text doesn't match UI

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#336]
Text states:
(4) Select Accounts, and then select Access work or school. (5) In Access work or school, select Connected to contoso….

However, this is what I see:
![image](https://user-images.githubusercontent.com/4753203/32997221-6291bd86-cd52-11e7-9477-85db232efd89.png)

Works fine except for the name/label

**Comment by Anghus** [comment]
Please update text to avoid confusion.

**Comment by pr-honey** [comment]
Fixed
