### ISSUE TITLE
Task 1.6: Never recieved subtasks 2 and 3

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#340]
I went straight to 4,most likely because I had already done those steps in previous labs:
(1) On Set up a PIN, select Set up PIN. (2) On Help us protect your account, select Set it up now. (3) On Verify your identity, in Pick a verification method, select Text message; in Select your country, select your country; in Phone number, type your mobile phone number, and then select Next. (4) On Enter the code you received, in Enter security code, type the security code you received, and then select Next.

**Comment by Anghus** [comment]
I think we need to make these steps generic, like Paul did, anywhere this appears. Thoughts?

________________________________

**Comment by DouglasSteen** [comment]
I'm a bit confused about what to change/fix. I understand previous labs have already done some of these steps. Is sub-task 1 necessary? If I delete sub-tasks 2 and 3 will the steps be right? 

Also, what exactly did Paul do to make them "generic"?

Let me know and I'll get this one fixed!

**Comment by networkingguru** [comment]
Doug, I don't have any better info on what Paul did; I have run through his labs since his last bug fix pass. For me, my recollection is that when I went through this step, I went directly to 4, so removing 1-3 would have matched what I saw.

**Comment by Anghus** [comment]
He basically just said "(4) If necessary, finish setting up your account by using the wizard to verify your identity" etc. Of course, you'll want to phrase in a way that makes sense for the lab.

**Comment by Anghus** [comment]
I think we're leaning towards just canceling on this. Clicking the X. Brian needs to verify which labs this appears in.

**Comment by DouglasSteen** [comment]
Leaving the task as is. I tried with one of Paul's tenants that he had already used with Intune (LODSE890547.onmicrosoft.com). The steps for joining the device to Azure AD was the same as currently document. I am unable to reproduce this issue.
