### ISSUE TITLE
Task 1.8: Directives do not match UI

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#341]
I believe this line:
(2) In Settings, select Settings, select System, and then select About. 

Should be this:
(2) In Settings, select System, and then select About.

**Comment by DouglasSteen** [comment]
Good catch!!! 

Updated the lab content to match the recommendation as follows:

**(1) Select Start, and then select Settings. (2) In Settings, select System, and then select About. (3) On About, verify that Organization is set to Contoso; then, select the Manage or disconnect from work or school link. (4) On Connect to work or school, select Connected to Contoso's Azure AD, select Manage your account; review the information for Lori (specifically, her enrolled devices), and then close Microsoft Edge. (5) Select Knowledge, and read the note. (6) Close Settings.**
