### ISSUE TITLE
Task 1.11: Substep 3 will probably not occur

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#343]
At this point, we have dismissed the Welcome splash in other labs.

**Comment by DouglasSteen** [comment]
Updated the task to remove the offending portion of sub-step 3. Updated text is as follows:

"(1) Open Internet Explorer, and then go to https://portal.azure.com (or select Type Text). (2) Sign in to the Azure Management Portal by using mark@domain.onmicrosoft.com with a password of Passw0rd. (3) On the left, select Azure Active Directory. (4) On Azure Active Directory - contoso, select Devices. (5) On Devices - All devices, verify that WIN10-E5-01 appears in the list of enrolled devices. (6) Select Knowledge, and review the note."
