### ISSUE TITLE
Task 2.1: Task is Incorrect

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#344]
We are already on DC and logged in as Mark. Either this task is superfluous and the next task should refer to IE instead of Edge (Edge is not on the server), or this task needs to refer to a different system.

**Comment by DouglasSteen** [comment]
Removed task 2.1 for signing in to DC as Mark. Also changed reference from Microsoft Edge to Internet Explorer in the "old" task 2.2.
