### ISSUE TITLE
Task 2.3: Information is misspelled

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#345]
(7) On Create your cloud instance, review the informatioin, and then select Continue.

**Comment by DouglasSteen** [comment]
Fixed spelling error. Updated task text is as follows:

"**(1) In Windows Defender Security Center, on Setup, select Next. (2) On Select the data storage location, select US, and then select Next. (3) On Select the data retention policy, select Next. (4) On Select your organization size, select Next. (5) On Select your industry, in Manufacturing and resources, select Discrete manufacturing, and then select Next. (6) On Preview experience, select Next. (7) On Create your cloud instance, review the information, and then select Continue. (8) Select Knowledge, and read the note.**"
