### ISSUE TITLE
Task 2.4: Save not an option

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#346]
Text for reference:
(3) In Internet Explorer, select Save as. (4) In Save As, go to D:\Source$, and then select New folder; in Name, type WindowsDefenderATP, and then select Save. 

You have to hit enter after typing the name, then double-click on it before save is an option.

**Comment by DouglasSteen** [comment]
Updated the text as follows:

"**(1) Select Knowledge, and read the note. (2) On Windows Defender Advanced Threat Protection is almost ready, under 1. Onboard an endpoint, select Download package. (3) In Internet Explorer, select Save as. (4) In Save As, go to D:\Source$, and then select New folder; in Name, type WindowsDefenderATP, and then press Enter. (5) In Save As, open the WindowsDefenderATP folder, and then select Save. (6) Close the Internet Explorer notification at the bottom of the page.**"
