### ISSUE TITLE
Task 2.9: Error writing to registry

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#349]
On subtask 5:
![image](https://user-images.githubusercontent.com/4753203/33001991-f2b25348-cd76-11e7-98f8-f13a26b77c09.png)

**Comment by networkingguru** [comment]
Additional piece of info: Local Lori can write to the registry fine.

**Comment by networkingguru** [comment]
Add alert to ensure user selects the correct path. In future labs, maybe a .reg file is a better answer? No chance of mistakes then.

**Comment by DouglasSteen** [comment]
Added the following Alert text to the task:

"**Ensure that you add the new registry value in HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection and not in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Advanced Threat Protection (propery registry path has "Policies" in the path.**"
