### ISSUE TITLE
Task 4.4: Should we remove authenticated users?

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#35]
In this task, we have the user add the Windows Hello for Business user group to the GPO's security filtering. We don't ask the user to remove the Authenticated Users group, however. Seems pointless to filter if we leave the Authenticated Users group in there.

**Comment by chris-howie** [comment]
Yep, totally agree. Strange I forgot to put that in the lab.

**Comment by chris-howie** [comment]
This is an issue with how the original lab was written. Keeping this open but lowering priority.
