### ISSUE TITLE
Task 3.7: Subtask 1 is kind of confusing

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#353]
(1) Restore File Explorer with \\DC\Source$\WindowsDefenderATP, and then double-click WDATP-Detection.txt.

I figured it out, but it wasn't obvious. Maybe just "Type \\DC\Source$\WindowsDefenderATP into Cortana"?

**Comment by Anghus** [comment]
I changed to "In File Explorer, open ..."
