### ISSUE TITLE
Task 3.9: Had to refresh twice

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#354]
Perhaps let users know it may take more than one refresh

**Comment by DouglasSteen** [comment]
Updated the task as follows:

"**(1) In Internet Explorer, refresh the Windows Defender Advanced Threat Protection is almost ready page multiple times until the Detection test (at the bottom of the page) has the status Completed, and then select Start using Windows Defender ATP. (2) Select Knowledge, and read the note.**"
