### ISSUE TITLE
Task 5.10: No unresolved alerts exist

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#360]
![image](https://user-images.githubusercontent.com/4753203/33005171-52195170-cd8a-11e7-8385-323fc27883d6.png)

**Comment by DouglasSteen** [comment]
Updated the task wording to instruct the attendee to resolve any unresolved alerts (if there are any). The updated task is as follows:

"(1) Select Knowledge, and read the note. (2) In Windows Defender Security Center, on the left, select Machines list. (3) On Machines list, select win10-e5-01. (4) On win10-e5-01, under Alerts related to this machine, review the alerts. (5) Resolve any unresolved alerts in the list by selecting ..., and then selecting Manage alerts. (6) On Manage alerts, under Alert status, select Resolved. (7) Repeat step 5 and step 6 for the remaining alerts."

Added an Alert for the task that helps guide the attendee as well. The Alert text is as follows:

"If you do not have any unresolved alerts, the you can skip this task."
