### ISSUE TITLE
Task 6.2: Folder does not exist

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#361]
Text:
(1) In File Explorer, go to C:\\Extras\OnlinePurchases, and then double-click MavenBooks-Invoice.doc. (2) On Password, in Enter password to open file, type WDATP!diy# (or select Type Text), and then select OK. (3) In Word, close Sign in; on SECURITY WARNING, select Enable Content; review the demo attack scenario message, and then select OK. (4) On WinATP-Intro-Backdoorexe.jpg, review the message, and then select Enter. (5) Review the contents of the Word document. (6) Select Knowledge, and read the note.

UI:
![image](https://user-images.githubusercontent.com/4753203/33005297-d16d370c-cd8a-11e7-8fed-47d54e452b9f.png)

**Comment by DouglasSteen** [comment]
Added Sales folder (with Word document) to WIN10-E5-01 and WIN10-E5-02.
