### ISSUE TITLE
Task 6.2: Got Word activation dialog

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#363]
![image](https://user-images.githubusercontent.com/4753203/33006382-cac0ae20-cd8f-11e7-9feb-bf1c456cd3b7.png)

**Comment by networkingguru** [comment]
Activated with Lori's account:
![image](https://user-images.githubusercontent.com/4753203/33006428-f5f5bde2-cd8f-11e7-8ae8-27840bf4eed4.png)

**Comment by networkingguru** [comment]
Got another intrusive dialog:
![image](https://user-images.githubusercontent.com/4753203/33006468-1378d714-cd90-11e7-9331-0c0f23ebdd2e.png)

**Comment by DouglasSteen** [comment]
Updated the task to activate Office as lori@domain.onmicrosoft.com with a password of Passw0rd. See updated task as follows:

"(1) In File Explorer, go to C:\\Extras\OnlinePurchases, and then double-click MavenBooks-Invoice.doc. (2) On Password, in Enter password to open file, type WDATP!diy# (or select Type Text), and then select OK. (3) In Word, on Activate Office, complete Office activation by using lori@domain.onmicrosoft.com with a password of Passw0rd. (4) On First things first, select Accept. (5) Select Knowledge, and read the note."
