### ISSUE TITLE
Task 6.2: Enable Editing before Enable Content

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#364]
Text states:
 (3) In Word, close Sign in; on SECURITY WARNING, select Enable Content; review the demo attack scenario message, and then select OK. 

However, before selecting Enable Content you must first select Enable Editing.

**Comment by DouglasSteen** [comment]
Split Task 6.2 into two tasks as follows:

First task:

"(1) In File Explorer, go to C:\\Extras\OnlinePurchases, and then double-click MavenBooks-Invoice.doc. (2) On Password, in Enter password to open file, type WDATP!diy# (or select Type Text), and then select OK. (3) In Word, on Activate Office, complete Office activation by using lori@domain.onmicrosoft.com with a password of Passw0rd. (4) On First things first, select Accept. (5) Select Knowledge, and read the note."

Second task:

"(1) On SECURITY WARNING, select Enable Content. (2) On Microsoft Word, review the demo attack scenario message, and then select OK. (3) On WinATP-Intro-Backdoorexe.jpg, review the message, and then select Enter. (4) Review the contents of the Word document. (5) Select Knowledge, and read the note. (6) Close Word."
