### ISSUE TITLE
Task 7.3: Unsure what the UI elements are

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#365]
Text says:
(3) On Suspicous Powershell commandline, beneath Alert process tree, review the information. (4) Under Incident graph, review the information.

I can't seem to find the Alert Process Tree or Incident graph. Doesn't help that the UI is super squashed at this resolution:
![image](https://user-images.githubusercontent.com/4753203/33006757-3794c53a-cd91-11e7-9b45-42f5d041bdbb.png)

Also, Suspicious is misspelled.

**Comment by networkingguru** [comment]
User needs to click on the Label for the event, not the checkbox beside it. This was not clear to me.

**Comment by DouglasSteen** [comment]
Fixed spelling error for "Suspicious".

**Comment by DouglasSteen** [comment]
Added an alert as follows to help guide the attendee on what to select:

"**Ensure that you select the title of the alert (Suspicious Powershell commandline, which is a hyperlink). Do not select the checkmark at the beginning of the alert row.**"
