### ISSUE TITLE
Task 8.4: More info about finding the file in quarantine would be appreceiated

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#369]
The file was removed incredibly rapidly for me, so much so that I needed to verify the quarantine. I did so with a little help from google, but it would be nice to have this info in the lab.

**Comment by DouglasSteen** [comment]
Updated Knowledge to include information about where to find a file after it has already been quarantined. The task text is as follows:

"After a few minutes, the malware file that you stopped and quarantined in Windows Defender Security Center will be placed in quarantine on the device. You can use the local Windows Defender user interface to verify that the file is in fact quarantined.
If WinATP-Intro-Backdoorexe.jpg is no longer in This PC/Desktop, then the malware file may already have been removed.  You can verify that the malware file is in quarantine by doing one of the following:

- In Windows 10, in the Windows Defender Security Center, select Virus & treat protection, select Scan history. On Scan history, under Quarantined threats, select See full history. The malware file will be in this list.
- In File Explorer, go to C:\ProgramData\Microsoft\Windows Defender\LocalCopy and the malware file should be in that folder."
