### ISSUE TITLE
General: There is no happy ending in this lab

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#37]
We do all of the configuration but never see the result. I'm sure we've discussed this already. Is there anything we can do to show the results of all their hard work? Low priority for tomorrow's event.

**Comment by chris-howie** [comment]
Yes, we talked about this. 1. We had to significantly cut the lab to fit within the page count and time (it is still much longer than the allotted time IMO). 2. The registration part is not in the original guide and there was neither budget nor time to add it.

**Comment by Anghus** [comment]
Correct. Leave the big open because I want to chase more funding for this.

________________________________
