### ISSUE TITLE
Task 8.6: No New found under Machine List

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#370]
When I click Machine list, I am immediately brought to the list, but the task states:
 (2) In Windows Defender Security Center, on the left, select Machine list, and then select New.

**Comment by DouglasSteen** [comment]
Removed ", and then select New" from the task. Task now reads as follows:

"**(1) Select Knowledge, and read the note. (2) In Windows Defender Security Center, on the left, select Machine list. (3) On Machine list, select win10-e5-01. (4) On win10-e5-01, under Machine timeline, review the event that relates to the WinATP-Intro-Backdoorexe.jpg file in quarantine.**"
