### ISSUE TITLE
Task 6.1: Knowledge about MDM policy is incorrect

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#371]
The default policy is (see screenshot):

* All users are enrolled in MAM when connecting.

* Any user in the Intune Users group is enrolled in MDM when connecting.

This might after the other knowledge in this lab regarding the URLs. Can the user be enrolled in both at the same time?

![mdm_scope](https://user-images.githubusercontent.com/16375526/33056820-5842fbf0-ce4d-11e7-9b79-1e5b26a42931.jpeg)

**Comment by chris-howie** [comment]
Added two clarifying knowledge sections (one on configuration and one on enrollment).
