### ISSUE TITLE
Task 2.3: Sending malware from personal email?

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#382]
Maybe I'm worrying too much, but it seems like a lot could go wrong with this (i.e. flagging their account, the sending server stripping the attachment before it even gets sent, etc.). Perhaps we should just have them create a burner account with a known entity to do all of this?

**Comment by Anghus** [comment]
Creating the burner account is a good idea but out of scope for a repurposed lab. I'm going to mark this as OOS but Next Release.
