### ISSUE TITLE
Task 5.2: Email is not present

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#394]
Both emails are listed in my sent items:
![image](https://user-images.githubusercontent.com/4753203/33081908-0521a1de-cea1-11e7-8538-245efdb1463a.png)

As an additional test, I sent one from my personal gmail account, and it showed up. Since I was using outlook.com for the first one (testymctrial@outlook.com, hit me up if you want the creds to test), I went back and repeated exercise 2 with gmail. I suspect outlook.com is doing something prior to sending it, or is filtering this account or something.

**Comment by networkingguru** [comment]
Additional info: I suspect the gmail message is also not going to come through, and may flag my account:
![image](https://user-images.githubusercontent.com/4753203/33082197-cd2e267a-cea1-11e7-8285-f7787e06ef41.png)

**Comment by Anghus** [comment]
I've run in to this before as well. It's hard to test because the email systems are pretty good at catching the viruses. What happens if we send from one tenant user to another?

**Comment by chris-howie** [comment]
I have never not gotten the links email. Are you saying you didn't get both?

**Comment by chris-howie** [comment]
I am considering not even emailing the safe attachment test anymore. I have tried so many attachments and they are either not found to be malicious or are not delivered even close to the amount of time. @Anghus - thoughts?

**Comment by networkingguru** [comment]
@chris-howie Yes, I didn't get either email from my Outlook account. I suspect it is because I sent the attachment one first, so I somehow got flagged after that. I certainly think that the safe attachments thing is better skipped. Like I mentioned earlier, unless we can figure out a way for this not to come back on people's personal accounts AND have it work reliably, there's just too many variables with it.

**Comment by Anghus** [comment]
Remove. Send need a note for the release notes. Add the release note flag to this bug and close.

________________________________

**Comment by chris-howie** [comment]
Yep - agreed. Removing this part.
