### ISSUE TITLE
Task 7.2: Did not get attachment

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#401]
I know this is somewhat expected, just letting you know. Based on my testing, I suspect it is being stripped at outlook.com before it is ever sent.

**Comment by Anghus** [comment]
It needs to be documented, though. I'm not sure why we're even doing the exercise if we can't get the email through. Maybe we just throw this in the release notes, fi there is nothing we can do about it. If that's the only solution, then label Release Notes.

**Comment by chris-howie** [comment]
I mention this multiple times in the lab. Safe Attachments takes a long time to test the attachment and it is expected that it will not be delivered during the lab.

**Comment by chris-howie** [comment]
Removing this step to avoid confusion. Adding details to release notes.
