### ISSUE TITLE
Task 8.1: Don't see the expected message

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#404]
Again, I know this is somewhat expected, just letting you know.

**Comment by Anghus** [comment]
I'm assuming you mean the email isn't there. Chris?

**Comment by chris-howie** [comment]
Safe Attachments takes a LONG time to scan an attachment and make a decision. I call this out in the lab. Not sure what else we can do other than ask the customer if they have a test attachment we could use instead that gets a faster decision or skip the attachment test.

**Comment by chris-howie** [comment]
Removing the send and verification for Safe Attachments because there is no way the participant will get it during the allotted lab time.
