### ISSUE TITLE
Task 1 Intro: Text is duplicated

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#406]
![image](https://user-images.githubusercontent.com/4753203/33084548-e7747f06-cea7-11e7-8245-8f80ac997d73.png)

If you scroll down, you see the duplicate text:
![image](https://user-images.githubusercontent.com/4753203/33084597-fc9ce616-cea7-11e7-9f54-b6e89c1c6a45.png)

**Comment by Anghus** [comment]
Looks like we found a bug in the platform. The text only appears once. Also, when I export the lab guide, it's only there once. Not sure where this is coming from. I'll document in the release notes. In the mean time, I'll throw this at @DouglasSteen to see if he can figure it out. If not, we need to file a bug report with LODS.

**Comment by DouglasSteen** [comment]
Copied the text from the first exercise introduction to Notepad. Then deleted the text from the exercise introduction. Then pasted the text back into the exercise introduction. 

Re-launched the lab and first exercise introduction seems normal (see screenshot).

<img width="960" alt="thorncastle-issue-406-exerciseintroductionduplicated" src="https://user-images.githubusercontent.com/31675871/33110512-3243c2bc-cefd-11e7-8d2d-b94ad9df728b.png">
