### ISSUE TITLE
Task 1.1: Got 'stay signed in' and 'save password' dialogs

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#409]
![image](https://user-images.githubusercontent.com/4753203/33084844-97a1a566-cea8-11e7-8627-1723c4fe1d67.png)

**Comment by Anghus** [comment]
Assumed knowledge.

**Comment by timwarner-hc** [comment]
Thanks, Jerry. I haven’t forgotten about this. I have this task as my very first TODO in the morning.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
