### ISSUE TITLE
Task 1.1: Why not use typetext to go directly to the admin center?

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#410]
This was commonly done in the previous lab, so going this route is a bit jarring directly after that lab

**Comment by Anghus** [comment]
Good point. Leaving for @timothywarner.

**Comment by timwarner-hc** [comment]
What is "typetext"? Because the default view in the tenant is the user's apps list, I figured it was straightforward enough to have them click the Admin tile from the apps list. @networkingguru , @Anghus

**Comment by networkingguru** [comment]
@timothywarner Typetext is the feature in LODS where you have the participant click a button to autofill some text, like a command or (in this case) a URL. If you are editing in LODS, it's a field on the task itself. You populate it with the text and check the box and it shows up.

**Comment by timwarner-hc** [comment]
Ok. How important is it to you for me to do that?

**Comment by Anghus** [comment]
Assign the bug to me. Are you sure it's still open? I did all those last night.

________________________________

**Comment by Anghus** [comment]
I took a look, and I think I'd rather they go through the menu.

**Comment by timwarner-hc** [comment]
Ok. You mean type text menu and not the app menu?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Anghus** [comment]
No. I closed the bug.

________________________________
