### ISSUE TITLE
Task 3.2: Step unclear

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#415]
The text states:
(1) In the list, select Concur; from its context menu, select Sanctioned. 

However, if you select Concur (by clicking on the name) it takes you to a report page for Concur. Instead, you must select the sideways ellipsis thing to the right:

![image](https://user-images.githubusercontent.com/4753203/33086020-0bc91f5c-ceac-11e7-9a54-20cb2ad9c276.png)

**Comment by timwarner-hc** [comment]
Adjusted the 3.2 instruction to ask the learner to open the vertical ellipses icon.
