### ISSUE TITLE
Task 4.2: Sanctioned filter not obvious

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#418]
Text states:
(4) In the filter bar under App Tag, select Sanctioned to filter the view to display only those apps you have sanctioned for your organization.

However, there s nothing that states 'Sanctioned', it's the little check box. 
![image](https://user-images.githubusercontent.com/4753203/33086341-e249c69e-ceac-11e7-9329-3e4bf786f228.png)

**Comment by timwarner-hc** [comment]
Edited the instruction to explicitly reference the circle-backslash button.
