### ISSUE TITLE
Task 6.1: Step not clear

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#421]
Step states:
(2) In the Policy list, select the Settings icon. (3) On the Edit anomaly detection policy page, select Cancel to return to the Policies page.

Unfortunately, there are three settings icons on this page. I assume it is the General anomaly detection one, and am continuing testing with that, but I think the step should be specific. 
![image](https://user-images.githubusercontent.com/4753203/33086614-b2374ef8-cead-11e7-97bc-7f28dcf34c05.png)

**Comment by timwarner-hc** [comment]
Adjusted instructions to specifically reference the Settings (gear) button.
