### ISSUE TITLE
Task 6.2: Task slightly unclear

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#422]
Task states:
(1) In the filtered template list, in the File containing PII detected in the cloud (built-in DLP engine) row, select Create Policy.

However, there is nothing labeled Create Policy. You must hover over the + to see that:
![image](https://user-images.githubusercontent.com/4753203/33086754-3e44c39e-ceae-11e7-9dc8-ded0c0337f51.png)

**Comment by timwarner-hc** [comment]
Altered the instruction to describe the plus sign icon.
