### ISSUE TITLE
Task 7.1: Edge hung on this task

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#425]
Recovered after choosing that option. However, kept up the spinning ball routine for several minutes:
![image](https://user-images.githubusercontent.com/4753203/33087069-226b8da0-ceaf-11e7-856f-2bfa26bdd77c.png)

Refreshing didn't change things.

**Comment by timwarner-hc** [comment]
Adjusted instructions to look at the built-in alert policies instead.
