### ISSUE TITLE
Task 8.1-8.2: Steps seem redundant

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#427]
The last step of 8.1 is:
(3) In the DLP Dashboard, from the top menu, select the gear icon.

The first step of 8.2 is:
(1) In Cloud App Security, from the top menu, select the gear icon, and then select Cloud Discovery Settings.

As far as I can tell, the step from 8.1 is redundant/unnecessary

**Comment by timwarner-hc** [comment]
Removed step 4 from procedure 8.1.
