### ISSUE TITLE
Task 2.3: Had to double-click the 'new' label to open

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#429]
Just double-clicking on the alert did nothing

**Comment by chris-howie** [comment]
I have noticed this happens sometimes. If you wait long enough, clicking the title works too. :/ This is a repurposed lab so I'm not sure how we want to proceed. @Anghus ?

**Comment by Anghus** [comment]
Let's add a tip or something in an Alert. While this is a repurposed lab, usability tips like these help us maintain good CSAT, which reflects on us and not the original lab author.

**Comment by chris-howie** [comment]
Added an alert
