### ISSUE TITLE
Task 2.7: New activity does not appear

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#431]
Waited over 15 minutes, and refreshed the console. Nothing ever showed up until I actually closed the browser and reopened the site.

However, this console is unusably slow. It might take a minute for a click to result in some action.

**Comment by chris-howie** [comment]
@Anghus

**Comment by Anghus** [comment]
The VM isn't resource constrained. We monitored memory usage on it, and it never gets beyond about 60% (something like that. I forget the exact number.) @DouglasSteen, did you check CPU usage? I'm thinking the VM performance is probably beyond our control.

**Comment by Anghus** [comment]
We might want to add an Alert that tells the student to close and reopen the site if they don't see it.

**Comment by chris-howie** [comment]
I think the performance issues are either disk or network related in this case. 

This alert is actually already there: It may take a couple of minutes for the new suspicious activity event to appear. If it takes more than two minutes, close and reopen the ATA Console.
