### ISSUE TITLE
Task 2.7: Two new activites appeared; unsure which one to open

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#432]
Text states:
(2) In the ATA Console, note a new suspicious activity. (3) Double-click the title to see details about the information the attacker was able to retrieve. 

UI:
![image](https://user-images.githubusercontent.com/4753203/33092659-646f6454-cec0-11e7-928b-dab8f2afe17d.png)

**Comment by chris-howie** [comment]
This definitely does not always happen. I would say the user would likely choose the most recent or both. Either option would be ok here. @Anghus  - Are you cool leaving as-is?
