### ISSUE TITLE
Task 7.6: Missing step to confirm

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#443]
![image](https://user-images.githubusercontent.com/4753203/33094479-f19b4cda-cec5-11e7-8c61-94040024c2da.png)

**Comment by chris-howie** [comment]
This does not show up in the lab anymore. Did you test the correct lab?

**Comment by Anghus** [comment]
The screenshot matches the lab guide, so I'm sure he was in the right lab. @chris-howie, what no longer shows up in the lab? The command? The prompt?

**Comment by chris-howie** [comment]
Strange, I did not see that task in the one I was correcting. @Anghus, please check it in so I can change it.

**Comment by chris-howie** [comment]
Fixed
