### ISSUE TITLE
Task 3.2: PIN setup request

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#444]
After verifying my account, it wanted me to set up a PIN. I advise having them skip this step by clicking the X on the PIN wizard. Trying to proceed ends up putting you in and endless cycle of trying to provide your password only to get stopped with a note that you must change your password on first logon.

**Comment by probichaux** [comment]
Hmmm. I didn't have that problem with the tenant I was using, which was one of the LODSExxxx tenants created during the SC1-1 lab. I can easily revise this though.

**Comment by networkingguru** [comment]
Addendum: At 3.3, I see we want to set up a PIN. I could not get this to work. It kept asking me to verify my password then telling me I needed to change it but not letting me change it.

**Comment by Anghus** [comment]
I had the same exact problem. I canceled the change password prompt and continued on without a hitch. Can we just skip this whole set up PIN, verify, change password thing? If so, Brian, can you put your fingers on all the locations/labs it appears?

**Comment by networkingguru** [comment]
Well, odd. Kind of at a loss as to what to do. I can remove the account and then reconnect to see if I can get past the process. Not sure how central this issue is or how reproducible it is.

**Comment by probichaux** [comment]
PIN setup isn't required, I don't think. I didn't see it in the tenant I hand-created to write against, nor did I see it until after I added BYOD to management. I'm guessing one of the default policies enables Hello, which is triggering the PIN policy.

**Comment by networkingguru** [comment]
Jerry, the only way for me to find every occurrence of this thing is to go back through all of the labs metadata. I can certainly do that, but it's going to take a while.

**Comment by networkingguru** [comment]
@Anghus, Do you want me to just proceed without doing the PIN thing and test everything else? Or hold until we figure out how to handle this issue?

**Comment by pr-honey** [comment]
I’m modifying the IDL now—give me 5 minutes.

**Comment by probichaux** [comment]
OK, it's fixed. Assigning back to @networkingguru
