### ISSUE TITLE
Task 3.4: Incredibly long reboot

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#448]
This is the first time it's happened, and I'm not sure it's reproducible, but the reboot this round hung. I waited 25 minutes and it was still on 'Wait while Windows prepares your computer. Do not turn off.' 

I turned it off. 

I went through the event log, but could not find a root cause.

**Comment by Anghus** [comment]
I think there is something going on in the datacenter. It's random. I'll ask LODS to look in to it. Regardless, it's likely beyond our control. I already have something in the release notes as well.
