### ISSUE TITLE
HOL-SC2-3E (Cloud app security) Intro needs to be updated in the profile

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#450]
The current lab profile has a Windows Store for Business goal, scenario, etc. Needs to be updated. I believe Tim did provide front matter, and it's in Teams.

**Comment by DouglasSteen** [comment]
Which lab is this?

**Comment by DouglasSteen** [comment]
Updated the lab description, objective, and scenario based on edited front matter document in Teams.
