### ISSUE TITLE
General: Verify Jerry's changes to the lab guide

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#47]
I made numerous changes to the lab guide to fix bugs, correct typos, or to split multiple command entries in to separate tasks. Please compare and validate my changes.

**Comment by chris-howie** [comment]
Did you make the changes in the MD or only in LOD?

**Comment by Anghus** [comment]
We disconnected the labs from GetHub for now. Edit in the IDL Studio.

________________________________
