### ISSUE TITLE
General: Exercises must have more than one task

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#48]
Exercises must have more than one tasks, just like bulleted lists must have more than one bullet. The solution for this lab is to either split some of the tasks in to multiple tasks or combine some of the exercises.

**Comment by pr-honey** [comment]
I'm a little confused-- a quick scan for SC1-3B shows that all of the exercises have multiple tasks:

- Explore: understand, understand
- Configure: sign in, enable, create
- Create: create, set, create, set, assign
- Enroll: open, connect, install, enroll, connect, restart
- Create: create, specify, select, add, add
- Test: test, test

**Comment by Anghus** [comment]
Are you running the lab? Each exercise had one task with several steps in each. Not critical today, since we failed the lab. I'll try to get you a screenshot of the running lab later.

________________________________

**Comment by Anghus** [comment]
Closing this. The markdown wasn't rendering properly, I suspect. Either that, or I was overly tired, because it sure looks different today than it did last night.
