### ISSUE TITLE
Task 2.2: Block on Silverlight installation

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#50]
I can't continue testing this lab, because either (1) using the classic Intune portal requires Silverlight installation or (2) the instructions need to be rewritten to use Intune on Azure. I prefer that we use Intune on Azure from now on, as the classic portal is being deprecated. Please update the lab, and then step through to make sure everything works properly. I'm moving this lab back to the Develop phase for now. Once it's ready to test again, we'll turn Brian loose on it.

**Comment by pr-honey** [comment]
I'm looking at this now but what I see in GitHub doesn't match what's in LODS-- the LODS version has the student go to manage.microsoft.com. I am guessing Doug or you made some changes that haven't been propped back to GitHub yet?

**Comment by Anghus** [comment]
We disconnected it from GitHub. You'll have to edit in the IDL Studio. Wait until Doug fixes the Silverlight install, unless you think you can convert it to use Intune on Azure. If you're unsure about editing in the IDL Studio, hold off for today and I'll find you a good tutorial.

________________________________

**Comment by DouglasSteen** [comment]
Need to run any Silverlight-based apps on DC. Rework lab content to use DC for Azure/Intune/Office 365, not the Windows 10 clients.

**Comment by Anghus** [comment]
We have a new version of this lab, so this bug no longer applies.
