### ISSUE TITLE
Task 1.3: No HIPAA Safegaurds shortcut found

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#53]
I logged on to all 3 VMs as Mark, shortcut was not present.

**Comment by pr-honey** [comment]
Doug was going to create this shortcut in the lab VM.

**Comment by Anghus** [comment]
That’s why the bug is assigned to him ☺

**Comment by Anghus** [comment]
I replaced the shortcuts with URLs and **Type Text** elements. I'd prefer this over file baggage we might have to carry around.
