### ISSUE TITLE
Task 1.2: Getting a restart to apply updates message

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#66]
![image](https://user-images.githubusercontent.com/4753203/31523571-ee31a96a-af79-11e7-8d8d-2e025d29c5da.png)

**Comment by Anghus** [comment]
We don't need updates enabled in this series. I vote that we disable updates if we can.

**Comment by Anghus** [comment]
This is addressed in an Alert. For now, we'll ignore. Would be great to fix later. Marking Low.

**Comment by Anghus** [comment]
We've disabled Windows Update in the VMs.
