### ISSUE TITLE
Task 1.3: There's a LODS Properties text blob

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#67]
Pops up in the exercise conclusion box, it appears.

**Comment by Anghus** [comment]
This should be an easy fix. There is probably a bad URL stuck in the exercise.

**Comment by Anghus** [comment]
I fixed by editing each exercise to remove the extra text. There was **Switch to VM** markdown out of order in the file and it got sucked up in to the Conclusion text.
