### ISSUE TITLE
Task 5.7-11: Why not bulk reset the passwords?

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#7]
Rather than having the student reset each user's password individually, we can save a lot of time by bulk resetting the passwords.

**Comment by Anghus** [comment]
Saving this for a future version of the labs.

**Comment by DouglasSteen** [comment]
You can only "bulk reset" passwords to another "random" value and not to a known value (like "Passw0rd"). That is why each password is reset individually :)

**Comment by Anghus** [comment]
Closing based on Doug's comments.
