### ISSUE TITLE
Task 4.1: Missing steps

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#75]
This task says to do something in Azure Information Protection, but is missing all of the bits about how to get there.

**Comment by networkingguru** [comment]
Piggybacking on this, I tried to just go to the Azure portal, but the account doesn't have a subscription. I have a code, but I have never been through the steps to set it up, so potentially all of that is missing as well.

**Comment by Anghus** [comment]
Adding Doug, because we apparently need to activate the Azure passcode. Brian, the code was the one that you copied when you got your credentials in the first lab. Can you try that one and see if it works?

**Comment by Anghus** [comment]
Back on this again. I was able to get to Azure Information Protection just fine. However, the templates were missing. I'm not sure why your account didn't have a subscription if you're using the prebuilt tenant. Let's investigate.

**Comment by pr-honey** [comment]
That is super weird-- I didn't think you *could* have AIP in the tenant and not have the templates available.

**Comment by Anghus** [comment]
Agreed. Very strange. Were you able to repro?

________________________________

**Comment by pr-honey** [comment]
Closing, as this is against the original version of the lab, which has been replaced with the job aid version.
