### ISSUE TITLE
General: VM Needs more RAM

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#80]
If you use Edge instead of IE, the portal basically won't open. I believe this is a resource issue.

**Comment by Anghus** [comment]
Which VM would this be? We need a little more detail on bugs like these.

**Comment by networkingguru** [comment]
Sorry, there's only 1 in this lab: BYOD

**Comment by Anghus** [comment]
Particular for Doug and me, we're not usually looking at the lab guides when we triage these. So details like that are helpful. :)

**Comment by Anghus** [comment]
Documenting performance in the release notes. It's outside our control.
