### ISSUE TITLE
Task 1.3: Safe Attachments not found

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#81]
It says this should be under threat management, but is not:
![image](https://user-images.githubusercontent.com/4753203/31527159-0b29bb68-af91-11e7-8a4c-e39053220f44.png)

**Comment by networkingguru** [comment]
FYI, it's under Policy>ATP Safe Attachments

**Comment by chris-howie** [comment]
O365 changed between writing and testing the lab :( Updated
