### ISSUE TITLE
Task 2.3: Attachment does not exist

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#83]
The attachment you need to use to trigger the malware protection isn't present. 

![image](https://user-images.githubusercontent.com/4753203/31527397-83ee9018-af92-11e7-84d0-ca145d3502b3.png)

**Comment by Anghus** [comment]
Added @chris-howie as well.

**Comment by chris-howie** [comment]
changed the lab to not need this
