### ISSUE TITLE
Task 4.9: Do not see expected result in ATA

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#85]
The expected result is a log entry for "Identity theft using pass-the-ticket attack." However, after waiting a good amount of time, this log entry doesn't appear. Since this doesn't block the rest of the lab, prioritizing this as medium for now and moving on to the rest.

**Comment by chris-howie** [comment]
I got this in the past, but I think it is a timing issue. In the original lab, it says it can take 2 hours to show up >_< I modified the guide to not check for this event, just in case if it doesn't show up.
