### ISSUE TITLE
Task 7.6: Not prompted to press "Y"

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#86]
The task contains: "When prompted to confirm, type Y and then select Enter."

However, I was never prompted to confirm anything.

**Comment by Anghus** [comment]
It's possible that this is related to the other bug. That is, if an event isn't in the log, it can't be closed. Nothing to confirm. Retest this issue after fixing the other bugs first.

**Comment by chris-howie** [comment]
I removed this part of the task
