### ISSUE TITLE
General: Lab is light content

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#87]
The lab is pretty light on content. It's targeted for a 30 minute time slot (15 pages) but currently sits at 4 pages. We need to beef it up a good bit. @jerozoo, if you can connect @pr-honey with Dave Field, he can give Paul some ideas on how to beef this up.

**Comment by Anghus** [comment]
On hindsight, I don't think we need to bug Dave. Just pick a small number of additional settings. Maybe configure a policy in Intune. Let's try to get the page count to at least 10 pages.

**Comment by pr-honey** [comment]
Updated to add more material-- reviewing admin safeguards, then creating a simple MAM policy.
