### ISSUE TITLE
Task 3.1: Blocked on joining device to Intune

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#90]
The task says, "(5) In Access work or school, select Connected to contoso…. (6) Select Info. (7) Select Sync." It assumes that the device is already connected to Intune management. That will not be the case, as the VMs are reset after every lab. You will need to add a task to join the computer to Intune. See HOL-SC1-3D for a good example of the steps.

**Comment by pr-honey** [comment]
This task is missing from the IDL-- it's in GitHub.

**Comment by pr-honey** [comment]
Assigning to Doug for triage.

**Comment by pr-honey** [comment]
Updated to add a task to Intune-join the machine.
