### ISSUE TITLE
Task 7.2: Task doesn't match experience

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#92]
The task says, "(1) In Outlook, in the Inbox, you should not have received the message sent in the previous task, since the policy was set to block malicious attachments. (2) Select Knowledge, and read the note." However, the email message was received. Clicking on the attachment shows a message saying that the attachment was blocked. Additionally, there is no Knowledge box here. I removed the reference to it for now.

**Comment by chris-howie** [comment]
changed
