### ISSUE TITLE
Task 8.2: Task doesn't match the experience

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#93]
The task says, "(1) In Outlook, in the Inbox, notice a message you sent in the previous task that was redirected. (2)  Select Knowledge, and read the note." However, no message was received.

**Comment by Anghus** [comment]
One note. I suspect that outlook.com blocked the attachment before it every made it to Office 365.

**Comment by chris-howie** [comment]
Per the alert, it can take a long time for the redirection to happen. That is why I said in the alert that it may not show up for up to 30 minutes.
