### ISSUE TITLE
General: Lab content is light

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Thorncastle#96]
This one, too, is a little bit light. Our target is 15 pages to fill 30 minutes. Right now we're at 6 pages. Maybe we can expand some of the planning a bit? Or, add an exercise to plan the content of a capstone video to be published on YouTube? Maybe a bunch of questions to ask and answer in the video? If you need to talk to Dave about expanding this one, @jerozoo can hook you up.

On a related note, some of the tasks are at a bit more of a macro level. We like to be at a lower level most of the time. For example, instead of saying "Open Excel and paste the credit card numbers in a new spreadsheet," split that out in to a steps: "(1) Click Start > Excel 2016. (2) Select XXX to create a new spreadsheet. (3) Select Ctrl+V to paste the credit card numbers from the clipboard to the spreadsheet." It can be jarring for students when the level changes between labs, so we try to keep things pretty even across the board. Even though it seems laborious to read.

**Comment by jerozoo** [comment]
Not sure why these are coming to my personal email...

Elsa Rosenberg

**Comment by jerozoo** [comment]
Never mind--GitHub is signed up under our personal accounts. Have posted the message to the HOL's Team's tab.

**Comment by Anghus** [comment]
This is the account you accepted my GutHub invitation with. I can remove you and send you another invitation.

However, please reopen this bug into Paul has addressed it. He is also assigned to the bug. I added you for tracking to arrange time with Dave.

________________________________

**Comment by jerozoo** [comment]
Into his Teams HOL conversation. Fine with it being at jerozoo

 

Elsa Rosenberg

jerozoo@comcast.net

**Comment by pr-honey** [comment]
Jerry should review the current lab build since we've replaced it with the job aid-- might be OK to close it.

**Comment by pr-honey** [comment]
Closing since this issue is against the old version of the lab.
