### ISSUE TITLE
Task 1.9: Unclear what the screenshot is supposed to show

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#97]
Looks like just a screenshot of the environment with no explanatory text. Participants have already used screenshots at this point, so I'm not sure what this is supposed to help with.

**Comment by Anghus** [comment]
I understand why the screenshot is there: It's to show the Content tab. The solution is to highlight or point at the Content tab in the screenshot. Pushing this out for another release.
